[IV-23-24] Objetivo 0
MarioGuisado/TrainMe pull request #1
Opened 2023-09-15 11:59 UTC by MarioGuisado

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
* [x] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-15 15:38 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?
> 
>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?
> 
>     * [x]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
>       todo?

Porfa, mira bien lo que has marcado y además explica brevemente por qué has marcado cada uno de ellos.

2023-09-15 15:39 UTC, JJ requested changes
En ingeniería hay que partir de un problema, no de lo que quieres hacer. Por eso se ha hecho el juego de rol.

2023-09-15 15:39 UTC, JJ commented on README.md
> +El objetivo es implementar y desplegar una aplicación en la nube que ofrezca a los usuarios una plataforma de estudio colaborativo. Además se generarán de forma personalizada, alertas de descanso y s
No pido que describáis el objetivo, sino el problema.

2023-09-16 16:44 UTC, MarioGuisado commented
Listo para revisión.

2023-09-16 18:11 UTC, JJ requested changes
Es necesario formular un problema. Si necesitas que repitamos el juego de rol la próxima sesión, se podría intentar hacer. Si no, simplemente usa las fichas y trata de hacer esa fase de empatización tú mismo, para identificar claramente cuál es el problema y contarlo aquí.

2023-09-16 18:11 UTC, JJ commented on README.md
> +Al cliente, que pasa muchas horas estudiando/trabajando, le gustaría tener una forma de pautar sus descansos y rutinas saludables durante estos intervalos. Además, quiere tener una forma de conectar
Sigues sin describir el problema. Pautar los descansos no es un problema, es una posible solución a algo. Y además, añades "forma de conectar". ¿Qué problema resuelve eso?
En todo caso, se trata, como en el juego de rol, que describáis un problema, no diferentes cosas que se van a hacer.

2023-09-16 18:18 UTC, MarioGuisado commented
Listo para revisión.

2023-09-16 18:26 UTC, JJ requested changes
Si te ayudó la actividad del juego de rol, la podemos repetir la semana que viene con otras personas que estén en la misma situación. Si no, trata de buscar un verdadero problema que cumpla los requisitos que has puesto en el cuerpo del PR.

2023-09-16 18:26 UTC, JJ commented on README.md
> +El problema a resolver es la inactividad fisica y falta de descanso adecuada entre los estudiantes y trabajadores durante sus periodos de estudio/trabajo. Además muchos de ellos desearían poder coord
En general, cualquier problema que esté ligado a dispositivos físicos no va a ser adecuado para esta asignatura, y no veo cómo se puede detectar esa inactividad de otra forma. Y si se pudiera hacer, no veo de qué forma esto podría tener una lógica de negocio compleja, más allá de si no hay actividad, proponer actividad. 
Cada vez que usas "además", estás evidenciando que no estás presentando un problema, sino diferentes cosas que quieres hacer. Sólo hace falta *un* problema para esta asignatura.

2023-09-16 18:43 UTC, MarioGuisado commented on README.md
> +El problema a resolver es la inactividad fisica y falta de descanso adecuada entre los estudiantes y trabajadores durante sus periodos de estudio/trabajo. Además muchos de ellos desearían poder coord
Listo para revisión.

2023-09-16 19:09 UTC, JJ reviewed
Por favor, lee tranquilamente el guión, consulta la [lista de errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md) pero sobre todo y más importante, revisa la lista de comprobación uno por uno, justificando uno por uno todos los aspectos que se mencionan.
Cuando lo hayas hecho así, te lo corregiré de nuevo.

2023-09-16 19:09 UTC, JJ commented on README.md
> +El problema a resolver es el del manejo y gestión de las finanzas personales.
De veras, trata de leer cuidadosamente el guión y seguir la lista de comprobación. Esto ni siquiera se puede calificar como la descripción de un problema.

2023-09-16 19:29 UTC, MarioGuisado commented
Listo para revisión. He leído todo y he comprobado y actualizado la lista de requisitos. He actualizado el problema para que se centre en una cosa concreta: cómo puede un determinado cliente invertir de la mejor manera su dinero, qué estrategias puede seguir y en qué activos le interesa invertir. Un problema real y que no se soluciona solo buscando  y almacenando, sino que tiene una lógica de negocio detrás.

2023-09-17 09:41 UTC, JJ requested changes
Sigues sin formular el problema. Es imposible emprender un proyecto con esta descripción.

Un problema debe incluir:

* Una descripción clara del contexto. En este caso, no hay contexto. Hablas de "un cliente", no dices qué tipo de persona es, qué cantidades de dinero tiene, pero lo más importante, qué problema tiene. ¿Su problema es que tiene demasiado dinero?
* Una descripción clara del problema que tiene esa persona. No mencionas ningún problema, sino qué quiere hacer "quiere invertir".
* Por último, tiene que aclarar, si es necesario desde el principio, qué tipo de mecanismos se podrían usar para resolver el problema. En este no está claro que no se pueda resolver con "buscar producto financiero que cumpla x".

En general, no puedes hacer una aplicación fintech en esta asignatura. Y te agradecería que miraras con un poco de más atención las preguntas que respondes, porque si no eres inversor o conoces a alguna persona que esté en la banca comercial y te pueda responder a todo tipo de preguntas, *no tienes conocimiento personal*. Contestar a las preguntas con la mayor sinceridad es la mejor forma de aprovechar nuestro tiempo, especialmente en este fin de semana.
Recuerda que el pasar este objetivo o no no es una evaluación, no estoy evaluando. Estoy tratando de ayudaros a superar el objetivo para que el desarrollo de los objetivos sucesivos sea lo más suave y eficaz posible. En el guión de este objetivo viene los objetivos con los que tiene relación y puedes consultarlos si quieres, pero siendo objetivo 0, es evidente que se necesita hacerlo con mucha precisión para podeer abordar con éxito el resto de los objetivos.
Como sugerencia, espera al jueves que viene que, junto con otras personas que no hayan encontrado un problema adecuado, podemos repetir el juego de rol.

2023-09-18 05:38 UTC, JJ reviewed
Por favor, consulta de nuevo [los errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md) y trata de evitarlos a la hora de proponer *un problema* a resolver con una aplicación en la nube.

2023-09-18 05:38 UTC, JJ commented on README.md
> +El cliente comenta que quiere invertir parte de su dinero en distintos activos financieros, pero no sabe cómo hacerlo ni en qué proporción.
"Invertir en activos financieros" es una solución, no un problema. Y una vez más, una solución que difícilmente consistiriía en algo más que "buscar activos financieros".

2023-09-21 06:54 UTC, MarioGuisado commented
Listo para revision.

2023-09-21 10:21 UTC, JJ requested changes
Por favor, completa un poco más la descripción del problema con lo que hemos hablado en clase. Como ya hemos dicho varias veces, "recopilar" información no crea un problema adecuado para esta asignatura; es el procesamiento el que lo hace, pero tendrás que especificar claramente cómo se procesaría la información si no está implícito.

2023-09-21 11:04 UTC, MarioGuisado commented
Listo para revisión. He puntualizado el procesado de los datos recopilados (clustering + algoritmo KMeans) para que no dé lugar a dudas la forma en la que se haría.

2023-09-21 11:44 UTC, JJ approved these changes
:+1: Igual que no lo tengo en cuenta para lo negativo, tampoco lo voy a tener en cuenta para lo positivo, lo que hemos hablado en clase. Lo que escribes es más o menos correcto. Pero tendrás que asegurarte de saber lo que estás escribiendo tanto en el objetivo 1, como sobre todo en el 4. Así que consulta bien cómo habría que procesar datos categóricos o datos con diferente rango de variación en vectores uniformes a los que se le puedan aplicar esos algoritmos.

2023-09-21 11:50 UTC, merged