[IV-23-24] Objetivo 4
MarioGuisado/TrainMe pull request #38
Opened 2023-11-09 12:31 UTC by MarioGuisado

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2023-11-12 16:48 UTC, Morad02 commented
La mayoría de los commits no siguen las buenas prácticas

2023-11-12 17:12 UTC, Morad02 requested changes
En líneas generales, creo que los tests están bien.  Corrigiendo los commits y lo comentado creo que se estaría más cerca del aprobado.

2023-11-12 17:12 UTC, Morad02 commented on docs/tests.md
> +
Las características que describes de estos candidatos son muy generales y no creo que sirvan mucho para eligir las herramientas más razonables. Si vas a elegir Chai como biblioteca de aserciones, creo que deberías hablar un poco de él.

2023-11-12 17:12 UTC, Morad02 commented on docs/tests.md
> +
Si la popularidad de las herramientas va a ser un criterio de elección deberías decirlo en el apartado correspondiente. Además, creo que la explicación de la elección debería ir en base a los criterios que has puesto al principio

2023-11-12 17:12 UTC, Morad02 commented on docs/tests.md
> +
No se justifica el por qué del uso de la CLI de Mocha para ejecutar los tests

2023-11-12 17:12 UTC, Morad02 commented on src/atleta.ts
Siguiendo la filosofía de código limpio y SRP (single responsibility principle). Una función solo debe encargarse de hacer una cosa y tiene que caber en un solo pantallazo. Viendo el constructor, vemos que no cumple con estos requisitos.

2023-11-12 17:12 UTC, Morad02 commented on src/entrenador.ts
>  }
Aquí pasa lo mismo,  no sigue las indicaciones del SRP y código limpio

2023-11-14 09:15 UTC, MarioGuisado commented on docs/tests.md
> +
Resuelto en https://github.com/MarioGuisado/TrainMe/pull/38

2023-11-14 09:15 UTC, MarioGuisado commented on docs/tests.md
> +
Resuelto en https://github.com/MarioGuisado/TrainMe/pull/38/commits/9efd049154e7d5dd672f5f4b252b2def7b7c2c85

2023-11-14 09:30 UTC, MarioGuisado commented on src/entrenador.ts
>  }
Corregido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/2903dc724509b5e09cf7bf3af6c74ef93dfc6ca7

2023-11-14 09:30 UTC, MarioGuisado commented on src/atleta.ts
Corregido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/2903dc724509b5e09cf7bf3af6c74ef93dfc6ca7

2023-11-14 09:38 UTC, MarioGuisado commented on docs/tests.md
> +
Todos los candidatos incluyen CLI, el usado será el que incluya el framework seleccionado.

2023-11-14 09:41 UTC, Morad02 approved these changes

2023-11-14 09:43 UTC, MarioGuisado commented
@JJ Listo para revisión.

2023-11-14 12:25 UTC, JJ requested changes
`npm run test` no funciona

```txt

> iv@1.0.0 test
> mocha test/*


Error: Cannot find module '../dist/entrenadordisponible.js'
Require stack:
- /home/jmerelo/Asignaturas/infraestructura-virtual/TrainMe/test/atletadisponible_expect.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/home/jmerelo/Asignaturas/infraestructura-virtual/TrainMe/test/atletadisponible_expect.js:2:30)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:428:15)
    at async formattedImport (/home/jmerelo/Asignaturas/infraestructura-virtual/TrainMe/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async exports.requireOrImport (/home/jmerelo/Asignaturas/infraestructura-virtual/TrainMe/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async exports.loadFilesAsync (/home/jmerelo/Asignaturas/infraestructura-virtual/TrainMe/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/home/jmerelo/Asignaturas/infraestructura-virtual/TrainMe/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async exports.handler (/home/jmerelo/Asignaturas/infraestructura-virtual/TrainMe/node_modules/mocha/lib/cli/run.js:370:5)
```

Tendrás que asegurarte de que mocha funcione bien con typescript; del tirón no tiene por qué hacerlo.

2023-11-14 12:25 UTC, JJ commented on iv.yaml
> +test: test/atletadisponible_expect.ts test/entrenadordisponible_expect.ts
Sólo debes poner un fichero de test.

2023-11-15 10:34 UTC, MarioGuisado commented on iv.yaml
> +test: test/atletadisponible_expect.ts test/entrenadordisponible_expect.ts
Corregido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/9a91a20c6e144ff30e2e7a37919c8eeeb648e152

2023-11-16 09:22 UTC, MarioGuisado commented
@JJ Listo para revisión, ignora la mezcla de imports y require.

2023-11-16 09:25 UTC, JJ commented
Yo entiendo que queráis pasar esto, pero de veras que deberíais tratar de poner mensajes de commit mejores que este [86c9822](https://github.com/MarioGuisado/TrainMe/pull/38/commits/86c9822bb1a9f778a90bd1ad4fe0b01cf3b4a9e6)

2023-11-17 12:30 UTC, MarioGuisado commented
@JJ Listo para revisión.

2023-11-17 13:09 UTC, JJ requested changes
El problema es que creo que has complicado el código un poco más de la cuenta, con lo que es complicado saber realmente si has seguido las HUs. Deberías tratar de simplificarlo; si tienes los tests y funcionan bien, deberían seguir funcionando.

2023-11-17 13:09 UTC, JJ commented on src/atleta.ts
> +    private validarModalidadEntreno(modalidadEntreno: Map<number, string>): void {
¿Seguro que no puedes hacer un poco de DRY aquí? ¿No se trata de validar cosas en un rango al fin y al cabo?

2023-11-17 13:09 UTC, JJ commented on src/entrenadordisponible.ts
> +        this._disponibilidad = true;
Estás usando como variables de instancia cosas que posiblemente deberían ser sólo llamadas a función. Igual, estás convirtiendo en una entidad un solo objeto valor, y lo habitual es que una entidad gestione agregados de objetos valor.

2023-11-18 18:51 UTC, MarioGuisado commented on src/atleta.ts
> +    private validarModalidadEntreno(modalidadEntreno: Map<number, string>): void {
Corregido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/59a30851bed890cd5317371184f8234495b92983

2023-11-18 19:25 UTC, MarioGuisado commented on src/entrenadordisponible.ts
> +        this._disponibilidad = true;
Corregido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/e8705558f25a233e2e52f0c2b1d51e79c1c475f8 Ahora que lo comentas creo que es mejor manejar estos agregados en la futura implementación final de la lógica de negocio. Por eso he eliminado los métodos relacionados con estas variables (que como dices solo debería ser llamadas a función) y he modificado los tests consecuentemente en https://github.com/MarioGuisado/TrainMe/pull/38/commits/1208e979cbc4133b4afc3a839b8232f88c9a86ce de forma que solo compruebo lo esencial antes de empezar a implementar dicha lógica.

2023-11-18 19:25 UTC, MarioGuisado commented
@JJ Listo para revisión.

2023-11-20 12:03 UTC, JJ requested changes
El problema principal, aparte de lo planteado, es que realmente no has implementado la lógica de negocio. Deberías haber creado un issue para hacerlo, y tratar de resolver el problema aquí. 
De hecho, los tests no comprueban nada relacionado con historias de usuario, sólo asignan valores y ven si los valores están bien asignados (que lo van a estar). Ni siquiera comprueban posibles errores o excepciones.

2023-11-20 12:03 UTC, JJ commented on iv.yaml
> +test: test/atletadisponible_expect.ts
¿Añadirle "expect" es la buena práctica en este sentido?

2023-11-20 12:03 UTC, JJ commented on package.json
> +    "test": "env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }' mocha -r ts-node/register 'test/*.ts'"
¿Seguro que no hay otra forma de configurarlo que no sea con una variable temporal de entorno? ¿No lo puedes poner en tsconfig.json?

2023-11-20 12:03 UTC, JJ commented on package.json
>      "@typescript-eslint/eslint-plugin": "^6.9.1",
Si no lo usas, ¿por qué no lo has desinstalado?

2023-11-20 12:03 UTC, JJ commented on src/atletadisponible.ts
> +    asignarDisponibilidad(disponibilidad: boolean): void {
Para empezar, esta clase se llama `AtletaDisponible`. Si puede o no estarlo, el nombre no sería correcto. Pero el problema mayor es lo ya señalado varias veces en el objetivo 2 (y que no sé por qué se me pasó aquí en concreto): los objetos valor deben ser inmutables, y si hay algún cambio de estado no pueden manejarlo ellos, sino una entidad de orden superior. Mira por favor [este error frecuente](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md):

> Los objetos valor son inmutables; no pueden incluir ninguna variable de instancia que indique que han cambiado de estado, por ejemplo disponible o completada. El hacerlo así indica un error en la modelización del dominio: son las entidades las que tienen que gestionar esos cambios de estado, usando las estructuras correspondientes que liguen el objeto valor (inmutable) con su cambio de estado.

Y mis disculpas por no haberlo visto antes.

2023-11-20 12:03 UTC, JJ commented on src/atletadisponible.ts
> +        if (typeof disponibilidad !== 'boolean') {
TypeScript comprueba los tipos para que tú no tengas que hacerlo.

2023-11-20 12:03 UTC, JJ commented on src/entrenadordisponible.ts
> +    asignarDisponibilidad(disponibilidad: boolean): void {
Exactamente igual que antes. ¿Te das cuenta que estás generando una clase nueva y código nuevo para algo que se podría gestionar directamente desde una entidad?

2023-11-20 12:03 UTC, JJ commented on src/entrenadordisponible.ts
> +        if (typeof disponibilidad !== 'boolean') {
... y además repitiendo código.

2023-11-24 12:41 UTC, MarioGuisado commented on src/atletadisponible.ts
> +        if (typeof disponibilidad !== 'boolean') {
Clase eliminada en https://github.com/MarioGuisado/TrainMe/pull/38/commits/52e53129ff8e38a684c9d16649026938917b94cf

2023-11-24 12:41 UTC, MarioGuisado commented on src/atletadisponible.ts
> +    asignarDisponibilidad(disponibilidad: boolean): void {
Clase eliminada en https://github.com/MarioGuisado/TrainMe/pull/38/commits/52e53129ff8e38a684c9d16649026938917b94cf

2023-11-24 12:42 UTC, MarioGuisado commented on src/entrenadordisponible.ts
> +        if (typeof disponibilidad !== 'boolean') {
Clase eliminada en https://github.com/MarioGuisado/TrainMe/pull/38/commits/fcd23769f0b8624964c28f1b60a99880b41fc3d5

2023-11-24 12:42 UTC, MarioGuisado commented on src/entrenadordisponible.ts
> +    asignarDisponibilidad(disponibilidad: boolean): void {
Clase eliminada en https://github.com/MarioGuisado/TrainMe/pull/38/commits/fcd23769f0b8624964c28f1b60a99880b41fc3d5

2023-11-24 12:42 UTC, MarioGuisado commented on package.json
>      "@typescript-eslint/eslint-plugin": "^6.9.1",
Resuelto en https://github.com/MarioGuisado/TrainMe/pull/38/commits/3c38aa9ff7e925c4f0880efe3c60e0f521eb4228

2023-11-24 12:42 UTC, MarioGuisado commented on package.json
> +    "test": "env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }' mocha -r ts-node/register 'test/*.ts'"
Resuelto en https://github.com/MarioGuisado/TrainMe/pull/38/commits/3c38aa9ff7e925c4f0880efe3c60e0f521eb4228

2023-11-24 12:48 UTC, MarioGuisado commented on iv.yaml
> +test: test/atletadisponible_expect.ts
Modificado en https://github.com/MarioGuisado/TrainMe/pull/38/commits/ddae5ed6f9af583fca3da11afe4277ef26c82e20

2023-11-24 12:48 UTC, MarioGuisado commented
@JJ Listo para revisión.

2023-11-24 16:41 UTC, JJ requested changes
Me temo que hay una serie de problemas con el código y deberías de considerar una serie de alternativas, partiendo de la reformulación de los issues (si es necesario). En algunos casos, tendrás también que aplicar buenas prácticas.

2023-11-24 16:41 UTC, JJ commented on src/atleta.ts
> +    getid(): number {
Usa CamelCase aquí.

2023-11-24 16:41 UTC, JJ commented on src/atleta.ts
> +    getfechaNacimiento(): Date {
En JS se pueden declarar los getters con `get <funcion>`. Si no lo haces, la vocal después de `get` tiene que ir en mayúsculas.

2023-11-24 16:41 UTC, JJ commented on src/emparejador.ts
> +    vector.push(usuario.getnivelRendimiento().values().next().value);
No entiendo muy bien. Si estás usando un `Map`, ¿por qué no estás accediendo por clave a cada valor? Si vas a acceder sólo a los valores, ¿por qué no usas un array?

2023-11-24 16:41 UTC, JJ commented on src/emparejador.ts
> +    vector.push(usuario.getnivelCompromiso().values().next().value);
Tampoco acabo de entender este `next`. ¿Estás usando un iterador que guarda el estado del cursos de una llamada a `procesarUsuario` a otra?

2023-11-24 16:41 UTC, JJ commented on src/emparejador.ts
> +    vector.push(usuario.getmodalidadEntreno().values().next().value);
Es que no entiendo muy bien. ¿Por qué hay un `Map` si sólo usas un valor y ni siquiera la clave?

2023-11-24 16:41 UTC, JJ commented on src/emparejador.ts
> +    let id_elegido = -1;
Esto *nunca* es buena costumbre. Usar un flag para indicar si se ha encontrado algo o no es un antipatrón. 
Puedes usar en TypeScript `filter` para filtrar, en vez de un bucle, pero nunca esto.

2023-11-24 16:41 UTC, JJ commented on src/emparejador.ts
> +    return id_elegido;
¿Y si es -1? Estás devolviendo un valor inválido.
Además, Javascript tiene la función `sort`

2023-11-24 16:41 UTC, JJ commented on src/entrenador.ts
> +    private _modalidadEntreno: Map<string, number>;
Si estas variables de instancia son las mismas para Entrenador y Atleta, ¿por qué no usas la misma clase? Para eso está la herencia. Aunque en este caso ni siquiera tengo muy claro que realmente haya alguna diferencia, salvo un campo que siga si son entrenadores o jugadores o ni siquiera eso, simplemente que estén en diferentes arrays en el emparejador.

2023-11-24 16:41 UTC, JJ commented on src/types.ts
> +export const TipoContacto = new Map<string, number>([
¿De veras que vas a asignarle valor numérico al TipoContacto? ¿No deberías simplemente filtrar?

2023-11-24 22:00 UTC, MarioGuisado commented on src/atleta.ts
> +    getfechaNacimiento(): Date {
La clase ha sido eliminada en https://github.com/MarioGuisado/TrainMe/pull/38/commits/c46b36d275cd266f2952ce4dded300a04bddeb99

2023-11-24 22:00 UTC, MarioGuisado commented on src/atleta.ts
> +    getid(): number {
Aunque la clase ha sido eliminada, he incluido CamelCase en https://github.com/MarioGuisado/TrainMe/pull/38/commits/7e89f10b4d513a6de44272195ead7ec95a001c69

2023-11-24 22:02 UTC, MarioGuisado commented on src/emparejador.ts
> +    vector.push(usuario.getnivelRendimiento().values().next().value);
La verdad que el map me ha complicado de más las cosas, sobre todo viendo que luego solo iba a asignar un único valor a cada atributo. Los tipos estan corregidos en https://github.com/MarioGuisado/TrainMe/pull/38/commits/8efa73ea0cb658feaaf61c51afb9924e7a5bc8f6

2023-11-24 22:02 UTC, MarioGuisado commented on src/emparejador.ts
> +    vector.push(usuario.getmodalidadEntreno().values().next().value);
Tipos corregidos en https://github.com/MarioGuisado/TrainMe/pull/38/commits/8efa73ea0cb658feaaf61c51afb9924e7a5bc8f6

2023-11-24 22:03 UTC, MarioGuisado commented on src/entrenador.ts
> +    private _modalidadEntreno: Map<string, number>;
Clase eliminada en https://github.com/MarioGuisado/TrainMe/pull/38/commits/c46b36d275cd266f2952ce4dded300a04bddeb99

2023-11-24 22:04 UTC, MarioGuisado commented on src/emparejador.ts
> +    vector.push(usuario.getnivelCompromiso().values().next().value);
Clase corregida en https://github.com/MarioGuisado/TrainMe/pull/38/commits/2359ce8b9e0cc801ee4ab7f41ceac49ea3ce26ab

2023-11-24 22:04 UTC, MarioGuisado commented on src/emparejador.ts
> +    let id_elegido = -1;
Clase corregida en https://github.com/MarioGuisado/TrainMe/pull/38/commits/2359ce8b9e0cc801ee4ab7f41ceac49ea3ce26ab

2023-11-24 22:04 UTC, MarioGuisado commented on src/emparejador.ts
> +    return id_elegido;
Clase corregida en https://github.com/MarioGuisado/TrainMe/pull/38/commits/2359ce8b9e0cc801ee4ab7f41ceac49ea3ce26ab

2023-11-24 22:06 UTC, MarioGuisado commented on src/types.ts
> +export const TipoContacto = new Map<string, number>([
Los tipos están corregidos en https://github.com/MarioGuisado/TrainMe/pull/38/commits/8efa73ea0cb658feaaf61c51afb9924e7a5bc8f6

2023-11-24 22:13 UTC, MarioGuisado commented
@JJ Listo para revisión. He unido las clases en una única (Usuario), que tiene aquellos datos comunes y que serán los únicos necesarios para realizar los emparejamientos. Las iniciales clases separadas en entrenador y atleta quizás se deba a ideas un poco vagas y ambiciosas que tenía sobre lo que podría hacer la aplicación en el futuro según si el perfil era atleta o entrenador, en cualquier caso no eran necesarias para aplicar la lógica de negocio que es únicamente realizar el emparejamiento, por eso han sido unidas. Los tipos han sido redefinidos ya que no necesito realmente un map, puesto que cada dato solo va a tomar un valor. Las funciones del emparejador han sido corregidas siguiendo sus consejos y se ha aplicado CameCase como me comentó.

2023-11-26 09:41 UTC, JJ requested changes
Gracias por simplificar el código, pero me temo que no se trata tanto de simplificar como de usar las estructuras de datos más adecuadas a la lógica de negocio, tal como llevamos hablando desde el objetivo 2.

2023-11-26 09:41 UTC, JJ commented on src/emparejador.ts
> +    vector.push(usuario.GetNivelRendimiento());
Sigues repitiendo código. Y metiendo en el vector de la misma forma ¿el ID?

2023-11-26 09:41 UTC, JJ commented on src/emparejador.ts
> +    vector.push(usuario.GetPreferenciasContacto());
No creo que la preferencia contacto puedas incluirla en la medición de distancia. ¿No será simplemente una forma de filtrar unos y otros?

2023-11-26 09:41 UTC, JJ commented on src/emparejador.ts
> +    vector.push(usuario.GetModalidadEntreno());
La modalidad ¿es una forma de filtrar o una cantidad de la cual se pueda aplicar una distancia?

2023-11-26 09:41 UTC, JJ commented on src/usuario.ts
> +        this._nivelRendimiento = nivelRendimiento;
Por favor, Mario, recuerda lo que hablamos en el objetivo 2. Había algunas variables que servían para filtrar, y otras para calcular distancias. Estś metiendo todo en el mismo saco, hasta el id, para calcular distancias. ¿De veras que se elige el entrenador de esa forma?

2023-11-26 10:48 UTC, MarioGuisado commented on src/emparejador.ts
> +    vector.push(usuario.GetNivelRendimiento());
Corregido en https://github.com/MarioGuisado/TrainMe/issues/48 El emparejador guarda los datos de cada usuario y reserva la primera columna para el ID, de forma que se identifica fácilmente al usuario. No se utiliza para calcular la distancia.

2023-11-26 10:53 UTC, MarioGuisado commented on src/emparejador.ts
> +    vector.push(usuario.GetPreferenciasContacto());
Todos los datos (menos el ID) se pueden utililizar para calcular distancia (un atleta puede elegir que un entrenador con un nivel de compromiso distinto al suyo le sea sugerido), o se pueden utilizar para filtrar (solo los entrenadores con igual nivel de compromiso le serán sugeridos), creo que es lo que más sentido tiene en lugar de separar en datos para calcular distancia, y datos para filtrar, o al menos es lo que en una situación "real" me parece más natural. Las opciones de filtrado se han definido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/d37d539eb3c2a02ff3ebdfe6a30bdbd42e6dd81d y se han ajustado las funciones del emparejador para usar los filtros en  https://github.com/MarioGuisado/TrainMe/pull/38/commits/4197b8e49b4bb956ec846e229a99f48efdbfa1cd

2023-11-26 10:54 UTC, JJ commented on src/emparejador.ts
> +    vector.push(usuario.GetNivelRendimiento());
Tampoco es una buena práctica poner cosas diferentes en un array. Si no lo usas para calcular la distancia, usa otro método para identificar de quién se está hablando (como un hash)

2023-11-26 10:54 UTC, MarioGuisado commented on src/emparejador.ts
> +    vector.push(usuario.GetModalidadEntreno());
Ambos

2023-11-26 12:16 UTC, MarioGuisado commented on src/usuario.ts
> +        this._nivelRendimiento = nivelRendimiento;
Corregido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/515b37dc19085fb15122db15b7c0663b58d9a758

2023-11-26 12:17 UTC, MarioGuisado commented on src/emparejador.ts
> +    vector.push(usuario.GetNivelRendimiento());
Corregido en https://github.com/MarioGuisado/TrainMe/pull/38/commits/515b37dc19085fb15122db15b7c0663b58d9a758

2023-11-26 12:18 UTC, MarioGuisado commented
@JJ Listo para revisión. He creado un hash de forma que no se mezcle el ID del usuario con los valores que se usarán para filtrar y emparejar.

2023-11-27 06:39 UTC, JJ requested changes
Gracias por haberle dado una vuelta, creo que ha mejorado bastante. Creo que lo voy a dar por bueno, pero los dos errores son señalados son antipatrones importantes, así que convendría que los corrigieras antes de fusionar este PR o en todo caso antes del objetivo siguiente.

2023-11-27 06:39 UTC, JJ commented on src/emparejador.ts
> +    if(es_entrenador)
Si esto fuera la clave de un hash, no tendrías que hacer un if sino usarlo directamente para recuperar los valores

2023-11-27 06:39 UTC, JJ commented on src/emparejador.ts
> +    if (matriz_a_comparar == TipoMatriz.ENTRENADORES){
Igual, si usaras un hash indexado por el tipo podrías ahorrarte este if.

2023-11-27 06:39 UTC, JJ commented on src/emparejador.ts
> +    filtros.forEach((filtro) => {
Si usaras un map en vez de un `forEach` te devolverían los elementos directamente en vez de los índices.

2023-11-27 06:39 UTC, JJ commented on src/emparejador.ts
> +  GetUsuario(id_elegido: number, matriz_a_comparar: TipoMatriz): number[] | undefined {
en  CamelCase nuncas se pone la primera letra en mayúscula salvo qeu sea una clase.

2023-11-27 13:01 UTC, merged